<h2>Building Bridges. International Migration Services</h2>
<p>In 2011, the IB started to develop the International Migration Services – recruitment of skilled workers abroad – in order to help unemployed young adults from abroad to find a job in Germany. Annually, the IB helps around 200 young people into a career in Germany. The IB is offering modular services including language courses, integration services, accommodation and support to jobseekers. The well-trained and motivated experts learn German in intensive language courses and live in hotels, host families or in houses or apartments offered by the IB. The experts are recruited abroad and afterwards qualified for the labour market in Germany. Clients looking for experts, are supported by the IB partner organizations abroad, who are in charge of the preselection process. The recruitment of experts, e.g. nursing staff in clinics is implemented by the IB, its partner organisations and the client. A tailor-made requirement profile is created for the desired candidates. The companies determine the criteria for the profile in cooperation with the partners in the respective countries. Experts from Southern and Eastern Europe are mostly integrated into work. The selection of suitable specialists takes place after a preselection in the home country. IB particularly considers the qualification level of the respective applicants. They should have at least the required technical training, the relevant university degree or the required technical conditions. The IB also supports young adults from abroad to find an apprenticeship in Germany. Similar to the acquisition of skilled workers abroad, the IB is responsible for accommodation, language qualification, integration and support of the young people. The IB especially focuses on supporting regions with a high unemployment rate to ensure future perspectives for the young adults. Special attention is paid to the minimum qualifications of the candidates. A prerequisite is to have the A-levels (Abitur). The selection of suitable applicants is carried out together with the employer in the respective country. In some cases, funding opportunities are also available, for example, by the employment agency. An examination of the conditions is carried out in advance.</p>
<h3>Services:</h3>
<ul>
    <li>Accomodation</li>
    <li>Care and Support</li>
    <li>Half-board</li>
    <li>Integration</li>
    <li>Intensive Language Courses</li>
    <li>Recruitment in the respective country</li>
</ul>